#!/usr/bin/env bash

## Get const from file
#TG_ALERT_CHAT_ID, TG_URL, TG_PARSE_MODE
# we mighl start script from different locations
# +so use absolute path to config
CRED="$(dirname "$0")/credentials"
if [[ -s $CRED ]]; then
  . "$CRED"
else 
  echo "No credentials found at $CRED"
  exit 2
fi

show_help () {
cat << EOF
Usage: STDOUT | $0 [-sdlcv]
  -s 	Silent mode, no notification on message in telegram
  -d	Markdown parse mode, for using *bold* or _italics_
  -l    HTML parse mode, <b>bold</b> or <i>italics</i>
  -c	Send input as preformatted code block
  -v	Print curl output, e.g. telegram server response
Default parse mode: $TG_PARSE_MODE

Example: 
  ls -1 | $0 -sc
  df -h | grep sda | $0
EOF
}



OPTIND=1
while getopts "hsdlcv" opt; do
    case "$opt" in
      h) show_help; exit 0		;; 
      s)   silent="true"		;;
      d)   mode=${mode:="markdown"}	;;
      l)   mode=${mode:="HTML"}		;;
      c)   coded="true"			;;
      v)   output="/dev/stdout"		;;
      *)   exit 0			;;
    esac
done
shift "$((OPTIND-1))" 



# just sent text to TG
tg_send () {
  mode="${mode:=$TG_PARSE_MODE}"  
  if [[ $coded == "true" ]]; then
    if [[ $mode == "HTML" ]]; then
      msg="<pre>$1</pre>"
    elif [[ $mode == "markdown" ]]; then
      msg="\`\`\`$1\`\`\`"
    fi
  else msg="$1"
  fi

  curl -s -X POST				\
    "$TG_URL"					\
    -d parse_mode="$mode"			\
    -d chat_id="$TG_ALERT_CHAT_ID"		\
    -d text="$msg"				\
    -d disable_notification=${silent:="false"}	\
    --silent --output "${output:="/dev/null"}"
}
# if piped send message with text from stdin, else print usage note

if [[  -t 0  ]]; then 
  show_help
else
  tg_send "$(cat)"
fi

